package com.health.vax.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

/**
 * JPA entity mapped to the "patients" table (see skriptum chapter 12.1).
 * Annotations from Bean Validation (@NotBlank, @NotNull) are checked
 * automatically when a Patient is submitted with @Valid (chapter 13.3).
 */
@Entity
@Table(name = "patients")
public class Patient {

    // Primary key, generated by the database (auto-increment).
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // The name must not be blank; otherwise a validation error is raised.
    @NotBlank(message = "Name is required")
    private String name;

    @NotNull(message = "Birthdate is required")
    private LocalDate birthdate;

    // Social security number must be unique across all patients.
    @Column(unique = true)
    private long ssn;

    // One-to-many: one patient can have many vaccinations. The vaccinations
    // are stored in a separate table and reference the patient via
    // "patient_id" (see the mappedBy attribute and medical domain in ch. 12.2).
    // cascade = ALL: saving/removing a patient also applies to its vaccinations.
    @OneToMany(mappedBy = "patient", cascade = CascadeType.ALL)
    private List<Vaccination> vaccinations = new ArrayList<>();

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public LocalDate getBirthdate() { return birthdate; }
    public void setBirthdate(LocalDate birthdate) { this.birthdate = birthdate; }

    public long getSsn() { return ssn; }
    public void setSsn(long ssn) { this.ssn = ssn; }

    public List<Vaccination> getVaccinations() { return vaccinations; }
    public void setVaccinations(List<Vaccination> vaccinations) { this.vaccinations = vaccinations; }
}
